version: '3'
services:
  # edit .env file
  web:
    container_name: internal-${HOST_NAME}
    hostname: internal-${HOST_NAME}
    build: '.'
    volumes:
      - ../public_html/${HOST_NAME}:/home/public_html:rw
      - ../run/main/${HOST_NAME}:/home/run:rw
      - ../run/${HOST_NAME}/mysqld:/var/run/mysqld
      - ../run/${HOST_NAME}/redis:/var/run/redis
    environment:
      - HOST_NAME=${HOST_NAME}
    restart: unless-stopped # always
  redis:
    container_name: internal-redis-${HOST_NAME}
    hostname: internal-redis-${HOST_NAME}
    build: './redis'
    volumes:
      - ../data/${HOST_NAME}/redis:/data:rw
      - ../run/${HOST_NAME}/redis:/var/run/redis:rw
    restart: unless-stopped # always
  mysql-mariadb:
    hostname: internal-mysql-${HOST_NAME}
    container_name: internal-mysql-${HOST_NAME}
    build: './mysql'
    env_file: ./.env
    volumes:
      - ../data/${HOST_NAME}/mysql:/var/lib/mysql
      - ../run/${HOST_NAME}/mysqld:/var/run/mysqld
    restart: unless-stopped # always
networks:
  default:
    external:
      name: nginx-proxy
